[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
    
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
    
[[headers]]
  for = "https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
  [headers.values]
    Cache-Control = "public, max-age=604800"
